### ISSUE TITLE
mintty fails to compile with GCC 7.3.0

### ISSUE THREAD

**Issue by JPeterMugaas** [mintty/mintty#765]
I was trying to compile minty 2.8.5 under MSYS using gcc (GCC) 7.3.0 and I got this:

#cd src; make exe
#cd src; make bin
cd src; make
make[1]: Entering directory '/home/jpmugaas/msys/mintty/src/mintty-2.8.5/src'
gcc -c -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  -fstack-check child.c -o ../bin/msys64/child.o
gcc -c -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  -fstack-check term.c -o ../bin/msys64/term.o
gcc -c -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  termmouse.c -o ../bin/msys64/termmouse.o
gcc -c -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  -fstack-check wintext.c -o ../bin/msys64/wintext.o
windres -c 65001 --preprocessor 'gcc -E -xc -DRC_INVOKED -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG' res.rc ../bin/msys64/res.o
mv res.d ../bin/msys64/
termmouse.c: In function ‘term_mouse_release’:
termmouse.c:479:53: error: this statement may fall through [-Werror=implicit-fallthrough=]
     when MS_SEL_CHAR or MS_SEL_WORD or MS_SEL_LINE: {
                                                     ^
termmouse.c:540:5: note: here
     default:
     ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:136: ../bin/msys64/termmouse.o] Error 1
make[1]: *** Waiting for unfinished jobs....
child.c: In function ‘child_is_parent’:
child.c:516:29: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 12 [-Werror=format-truncation=]
       snprintf(fn + 6, 12, "%s/ppid", pn);
                             ^~
child.c:516:7: note: ‘snprintf’ output between 6 and 261 bytes into a destination of size 12
       snprintf(fn + 6, 12, "%s/ppid", pn);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:139: ../bin/msys64/child.o] Error 1
term.c: In function ‘check_emoji’:
term.c:1366:22: error: ‘sprintf’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]
     sprintf(ec, "%04x", emoji_bases[e.idx].ch);
                      ^
term.c:1366:5: note: ‘sprintf’ output between 5 and 7 bytes into a destination of size 6
     sprintf(ec, "%04x", emoji_bases[e.idx].ch);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:139: ../bin/msys64/term.o] Error 1
make[1]: Leaving directory '/home/jpmugaas/msys/mintty/src/mintty-2.8.5/src'
make: *** [Makefile:26: exe] Error 2

GCC 7.3.0 includes a number of warnings that would not be in earlier versions and this is likely to continue.

**Comment by k-takata** [comment]
Is that gcc compiled by yourself?
I think that the latest gcc targeting `x86_64-pc-msys` (MSYS2) and provided by MSYS2 is still 6.4.0.

**Comment by mintty** [comment]
On cygwin, gcc 7.3.0 is already available as a test package. I'm short from uploading an adaptation.

**Comment by JPeterMugaas** [comment]
I compiled the msys gcc 7.3.0 myself but I would suspect that could be an issue with other GCC 7.3.0 compilers and this is likely to get worse.  There is a warning about fallthrough that I've seen with GCC 7.3.0 for mingw with other software.  mintty is compiled to treat all warnings as errors and GCC 7.2.0 and later are tightening up their warnings.
