### ISSUE TITLE
Searching the scrollback

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#85]
```
Another Terminal.app feature that seems rather useful: the ability to
search the scrollback. Ctrl+/ is used to initiate that there.
```

Original issue reported on code.google.com by `andy.koppe` on 4 Apr 2009 at 7:52

**Comment by kiwiz** [comment]
@peaches @mintty Is there interest in getting this into MinTTY? If so, I'd like to take a stab at it. :)

**Comment by mintty** [comment]
Yes, any ideas how to do it? Blind search or Pop-up search form? Mark matches by selecting? Repeat search back/forward?

**Comment by kiwiz** [comment]
Coolbeans. So I've been working on kiwiz/mintty which implements this (it's based on @peaches' changeset).

Differences between the two:
- Ctrl+Shift+H opens the search bar.
- Doesn't highlight when no results are found.
- Supports arbitrary length queries.
- TAB returns to the terminal. (This causes a beep that I haven't figured out yet)
- Should update correctly when the terminal updates.

Notes:
- `attr` was turned into a `unsigned long long` (from an `int`) which isn't great... Wasn't sure where else to stick the new bits.
- Wide character support is broken. Determining how many cells a character takes seems to be tricky. There's also the case where a wide char is on the final cell of a line and an extra space is inserted.
- `in_search` could be more efficient. It currently does a linear search over the results array for every cell on the screen.

Screenshot: http://i.imgur.com/BuNc2p5.png

**Comment by mintty** [comment]
Hi Kai,
unfortunately, your code doesn't seem to compile here:
winsearch.c:145:7: error: initialization from incompatible pointer type [-Werror]
       .lpfnWndProc = search_proc,
       ^

Also, about the screenshot: Could it be possible to place the search input box above the window title, so the terminal screen area is not overlayed?
About attr: I'm currently reworking that anyway, so there would be more room for some bits if you need...
Further comments when I get the opportunity to try your patch, thanks.

**Comment by kiwiz** [comment]
Hello!

I've pushed a change to the fork that might fix the problem. Let me know if that successfully compiles. Fwiw, I'm on Windows 8.1 and it compiles successfully under Cygwin's gcc 4.9.2.

Regarding the searchbar: I was trying to mimic where Chrome and iTerm2's. I like the effect because it's small and out of the way. That said, it does hide anything on the top right of the screen. What are your thoughts on making it a separate window or just reserving an entire line when the searchbar is opened?

Good to know about `attr`. I'm currently using 2 bits, but I'm not sure if I'm making use of `TATTR_` as it was intended to be used. Will await further comments.

**Comment by mintty** [comment]
Hi Kai,
here is my feedback on your patch which I appreciate a lot. Don't get 
discouraged by the length of my feedback list...

To invoke searching, I would prefer something familiar like Alt-F3 or 
maybe Alt-Backarrow. The latter could possibly work independently from 
any Shortcuts option. The popup menu could also invoke the search...

If the search popup gets defocussed (e.g. by mouse-selecting something 
in a matched area, or simply clicking out), my idea would have been that 
the popup disappears. Is it on purpose that you leave it visible?

The input field should accept text from the paste buffer also by 
mouse-click.

I would place the back/forward fields left of the input field, for 
better contrast (esp. if the background is the same as the terminal 
screen background).

I would appreciate an explicit quit button ('X' field, left or right of 
the input field) as I'm sure people who don't often use the ESC key will 
complain.

About placement of the search pane, my idea was something like in the 
attached (faked) screenshot, if that's possible. If not possible 
directly, a separate window placed accordingly would do it as well.

If I click "previous match", on the very first match it does not scroll 
to it.

If I click out of the search box, sometimes match highlighting in the 
visible area (and a few more lines) is cleared while match highlighting 
in areas further scrolled away remains.

About wide characters: I see 啕 to work perfectly here. Which problems 
did you see?

Where does the "SearchBar" window class come from? I don't find it when 
checking e.g. 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633574%28v=vs.85%29.aspx#system
I guess that's preselecting the font and colours of the search field, 
maybe we can find something nicer.

Future enhancement: regular expressions?

Best regards,
Thomas

**Comment by kiwiz** [comment]
Not at all. I plan on seeing this through. Responses below:

Re: Invoking the search bar
I quite like the idea of having an entry in the right click menu. I chose <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>H</kbd> because <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> was taken (and <kbd>Ctrl</kbd>+<kbd>H</kbd> opens the 'replace' dialogue in some other text editors). Could we move Fullscreen to another button? Regarding <kbd>Alt</kbd>+<kbd>F3</kbd> and <kbd>Alt</kbd>+<kbd>Backspace</kbd>, I have no preference.

Re: De-focusing
Yup, this was intentional. The idea is that you could leave the search running and a streaming command (say `tail -f /var/log/syslog`) would highlight what you're looking for as it updates.

Re: Paste buffer
Do you mean right click + paste? That works fine for me.

Re: L/R Button & Close button.
Easy enough. Done. Granted, if we're moving this out to another window we can spread out the layout. Which brings us to...

Re: Search bar location
This should be possible, but the solutions I've seen look hacky. Additionally, I'm not a fan how this usually looks. Can I convince you that the current look or something like [this](https://3.bp.blogspot.com/-m-DG-r-jX6Y/UQfyPgnbF2I/AAAAAAAANDQ/Zx8sDFIpftA/s1600/sublime-text-3.png) is a good idea? I would prefer to keep everything in a single window.

Re: Matching issues
I think this broke when I added the "partial update" support. Will look into it.

Re: "SearchBar"
That's just the custom class I create. Maybe Consolas as an alternate font?

Re: Wide characters
Matching a single wide character works, but not multiple. This is due to the way `in_results` currently works (It tracks the number of _characters_, not _cells_, that would be occupied). I also need to account for the extra space that is created when a wide character is on the last column of a line and is "pushed down" to the next.

Re: RegEx
YES!

I moved the L/R buttons and added a close button because it was an easy change. Will work on the rest as I have time this week.

**Comment by mintty** [comment]
Hi Kai,
>
> Re: Invoking the search bar
> I quite like the idea of having an entry in the right click menu. I 
> chose Ctrl+Shift+H because Ctrl+Shift+F was taken (and Ctrl+H opens 
> the 'replace' dialogue in some other text editors). Could we move 
> Fullscreen to another button?
>
Most likely not. People are used to hotkeys.
>
> Regarding Alt+F3 and Alt+Backspace, I have no preference.
>
I would appreciate Alt+F3 and maybe Alt+Backspace additionally (and 
unconditionally by configuration).

> Re: Paste buffer
> Do you mean right click + paste? That works fine for me.
>
No, I mean the middle-mouse-button click (configurable).

> Re: L/R Button & Close button.
> Easy enough. Done.
>
Thanks. I've played around with this a little bit, see attached source. 
The value of 'margin' seems to be bound to 0 (strange vertical effect 
otherwise).

> Re: Search bar location
> This should be possible, but the solutions I've seen look hacky. 
> Additionally, I'm not a fan how this usually looks. Can I convince you 
> that the current look or something like this 
> <https://3.bp.blogspot.com/-m-DG-r-jX6Y/UQfyPgnbF2I/AAAAAAAANDQ/Zx8sDFIpftA/s1600/sublime-text-3.png> 
> is a good idea? I would prefer to keep everything in a single window.
>
Hmm, unsure yet. I still like my proposal. Your new proposal looks OK, 
too, but then the window would need to be resized when opening/closing 
the search bar which is a problem.

> Re: "SearchBar"
> That's just the custom class I create. Maybe Consolas as an alternate 
> font?
>
Consolas is nice but any specific font is kind of unmotivated. Maybe the 
font of the popup menu or some other system font, don't know which is 
taken now and I don't find how this could be configured anyway.
Or maybe simply the text font used in the terminal screen as the text 
refers to that?

> Re: Wide characters
> Matching a single wide character works, but not multiple.
>
I haven't checked multi-wide-character strings yet, but I checked the 
end-line wrap-around issue for a single one which seemed to work.

Kind regards,
Thomas

**Comment by kiwiz** [comment]
> Most likely not. People are used to hotkeys.

Fair enough. Added <kbd>Alt</kbd>+<kbd>F3</kbd> and a right click option. <kbd>Alt</kbd>+<kbd>Backspace</kbd> is in use for deleting a word so I left it alone.

> The value of 'margin' seems to be bound to 0 (strange vertical effect otherwise).

Should be fixed now.

> Consolas is nice but any specific font is kind of unmotivated.

I actually like the default font. That said, I've added some code to load up the font specified in the config.

Scrolling between search results should work now. I also tested out moving the search bar to the bottom and resizing the terminal on open/close.

**Comment by mintty** [comment]
Hi Kai,
thanks for the update. Here are my (unsorted) comments:

I think win_update_search should be called whenever the terminal size changes, right? If so, there are a few more places where it needs be called.
Unfortunately, just in that area there have been some modifications since your fork. Look for win_adapt_term_size. Maybe the update can be moved into that function.

Type Alt-keypad-6 in the search field, a question mark appears but the search still matches.

I would prefer the close button to look like a button (class "BUTTON") and to be placed on the other side than the left/right buttons. 
I’ve added three configuration alternatives to select button placement. Should I edit and provide that as a pull request?

How do you achieve the resizing of the terminal screen area?

You previously defined the geometry of the edit pane in CreateWindowEx, 
now you need a separate SetWindowsPos for it; is there a reason behind?

Match positioning does not always work yet. Type echo x, a number of new lines to scroll, another echo x, then search for x. When searching forward/backward, sometimes the first or second occurrence is not displayed when matched.

Match highlighting: strange effect: Have a lot of matches (e.g. ls -l in mintty src, then search for "win"), click into terminal screen area, one of the highlighted matches gets deselected.

Starting a search (typing anything, or reopening search bar) scrolls to top of scrollback buffer immediately. That may be confusing and not desirable.

If fullscreen is toggled (e.g. Alt-Enter), the search bar appears.

Additional features:
Desirable:
• Middle-mouse-click pasting.
• Search back/forward by keyboard (e.g. Alt-left/right).

Nice to have:
• Optional overlay placement in upper-right corner (like in previous patch version).
• Optional placement as window title overlay (I know, harder to do).
• Regex...
• Multi-line patterns (not necessarily expanding the input field).

**Comment by mintty** [comment]
Please note that I will be on holidays with limited access for the next weeks.
As a minimum for an initial integration into a mintty release I would point out the last two issues should be resolved:
Search bar appearing on full-screen toggle.
Scroll-to-top on opening pre-filled search bar.

**Comment by kiwiz** [comment]
Enjoy! I just got back from a trip. :)

I rebased the code against master and modified `in_results` to do a binary search. I'm not 100% sure I should be calling `win_adapt_term_size(false, false)`, but it seems to work fine...

> I think win_update_search should be called whenever the terminal size changes, right? If so, there are a few more places where it needs be called.

Fixed.

> If fullscreen is toggled (e.g. Alt-Enter), the search bar appears.

Ugh, this was a dumb bug. Fixed.

> I would prefer the close button to look like a button (class "BUTTON") and to be placed on the other side than the left/right buttons. 
> I’ve added three configuration alternatives to select button placement. Should I edit and provide that as a pull request?

Yup, that works. I've changed to a `BUTTON` for now.

> How do you achieve the resizing of the terminal screen area?

I resize the working area and compensate for the height of the search bar. You can see the relevant code on 403-405 of `winmain.c`. Could be cleaner imo.

> You previously defined the geometry of the edit pane in CreateWindowEx, 
> now you need a separate SetWindowsPos for it; is there a reason behind?

The width of the search bar resizes now so I moved that logic out of the initialization block.

> Middle-mouse-click pasting.

Done.

> Search back/forward by keyboard (e.g. Alt-left/right).

This is currently available as <kbd>Alt</kbd>+<kbd>Enter</kbd> and <kbd>Enter</kbd>. IMO, this is more standard.

> Starting a search (typing anything, or reopening search bar) scrolls to top of scrollback buffer immediately. That may be confusing and not desirable.

I agree that this is confusing, but iTerm does the same thing. Maybe only scroll once the user hits one of the arrows, <kbd>Alt</kbd>+<kbd>Enter</kbd> or <kbd>Enter</kbd>?

> Type Alt-keypad-6 in the search field, a question mark appears but the search still matches.

Fixed.

> Match positioning does not always work yet. Type echo x, a number of new lines to scroll, another echo x, then search for x. When searching forward/backward, sometimes the first or second occurrence is not displayed when matched.

Fixed.

> Match highlighting: strange effect: Have a lot of matches (e.g. ls -l in mintty src, then search for "win"), click into terminal screen area, one of the highlighted matches gets deselected.

Possibly fixed.

Will defer alternate layouts, Regex and multi-line patterns for now.

**Comment by mintty** [comment]
> I rebased the code against master
>
Great, thanks.
>
> and modified |in_results| to do a binary search. I'm not 100% sure I 
> should be calling |win_adapt_term_size(false, false)|, but it seems to 
> work fine...
>
>
>     I would prefer the close button to look like a button (class
>     "BUTTON") and to be placed on the other side than the left/right
>     buttons.
>     I’ve added three configuration alternatives to select button
>     placement. Should I edit and provide that as a pull request?
>
> Yup, that works. I've changed to a |BUTTON| for now.
>
Not in the archive I downloaded, but that's a minor thing I can tweak 
myself. Also I'd like to add style variations.
>
>     Search back/forward by keyboard (e.g. Alt-left/right).
>
> This is currently available as Alt+Enter and Enter. IMO, this is more 
> standard.
>
Alt+Enter could be OK (although some people might object that it's 
confusing regarding Alt+Enter in the terminal screen is the full-screen 
toggle), but doesn't work.
>
>     Starting a search (typing anything, or reopening search bar)
>     scrolls to top of scrollback buffer immediately. That may be
>     confusing and not desirable.
>
> I agree that this is confusing, but iTerm does the same thing. Maybe 
> only scroll once the user hits one of the arrows, Alt+Enter or Enter?
>
Yes.
>
>     Match highlighting: strange effect: Have a lot of matches (e.g. ls
>     -l in mintty src, then search for "win"), click into terminal
>     screen area, one of the highlighted matches gets deselected.
>
> Possibly fixed.
>
Maybe in the course of this fix, a crash condition has slipped in. I 
encounter it in two cases, only if there is scrollback available:
ls -l (in mintty/src, to generate some scrollback)
Alt-F3 win
click in terminal screen
→ crash
or:
Alt-F3 something
click in terminal screen
ls -l
→ crash

**Comment by kiwiz** [comment]
> Alt+Enter could be OK

Opps, it's actually <kbd>Shift</kbd> + <kbd>Enter</kbd> and <kbd>Enter</kbd>.

> Yes.

Coolbeans. Added.

> Maybe in the course of this fix, a crash condition has slipped in.

Fixed.

> Not in the archive I downloaded, but that's a minor thing I can tweak
myself. Also I'd like to add style variations.

Opps, jumped the gun.

I also noticed that the constants I was using in `term.h` are now in use. I bumped up the numbers by a few powers of 2 to compensate. Also, screen updates currently take `O(n logn)` time with `n = width * height`. I'll get rid of that `logn` and fix the remaining unicode issue.

**Comment by mintty** [comment]
I have uploaded the patch with some modifications. Search bar layout is configurable.
Please "rebase" for further additions.
I would appreciate one detail for the release: After Alt-F3 with preset search string, a first Shift+Enter should find the last, not the first match, I think.
How should I refer to you for the credits? Just "Kai (kiwiz)"?

**Comment by kiwiz** [comment]
Nice! I've had less time to work on things lately, but I'll work on the remaining issues when I do. Regarding credit, could you include my twitter (@sixhundredns) too?

The diff for that change is really small, so I'll just include it inline:
```
diff --git a/src/winsearch.c b/src/winsearch.c
index c43ce01..3305c94 100644
--- a/src/winsearch.c
+++ b/src/winsearch.c
@@ -56,6 +56,7 @@ prev_result(void)
     }
   }
   else {
+    term.results.current = term.results.length - 1;
     searched = true;
   }
   scroll_to_result();

```

**Comment by kiwiz** [comment]
Fixed wide character support in this commit:
https://github.com/kiwiz/mintty/commit/d5492c8c7a8214ba086e8db35f02f599dc5865b2

**Comment by mintty** [comment]
Released in 2.2.1.

**Comment by peaches** [comment]
:+1:, thanks for landing this.

**Comment by mintty** [comment]
Released search bar zooming and DPI scaling in 2.6.2.

**Comment by mintty** [comment]
If you search while the screen is scrolled back (in the scroll buffer, Shift+PgUp) *and* the screen is further appended to by continuous output, search behaves strangely and may even mark unmatching text.
(Minor issue.)

**Comment by mintty** [comment]
Released 2.7.5 with case-insensitive matching and fixed non-BMP support.

**Comment by mintty** [comment]
@kiwiz: If output scrolling continues while search highlighting is active, all highlighting remains at the previous positions, so highlighting the wrong text now (the matches have scrolled away under the highlighting). I have the idea that adding term_clear_search to term_scroll might help and planned to try that, but since you are more familiar with the details, maybe you could check out on this?
(And if you feel ambitious, I'd even have another request...)

**Comment by kiwiz** [comment]
@mintty Sure, I can take a look tomorrow.

Regarding the other request: Not sure if I can commit, since I don't have a lot of free time atm, but let's hear it.

**Comment by kiwiz** [comment]
@mintty Found it. The reason this occurs is due to a (buggy) optimization I implemented.

Let `c` be the number of visible rows, let `n` be the maximum lines of scrollback to keep.
This bug requires conditions to be met:
- You hit `c + n` lines, meaning old lines will get deleted if any new lines are inserted.
- A search is active with results.
- A new line is inserted.
When that happens, the code executes a `PARTIAL_UPDATE`, which only updates the last `c` (AKA, the visible) lines.
This is acceptable if you haven't reached `c + n` lines, as all the offsets in the result list to `term.lines` are valid. Once lines started getting dropped that is no longer true!

There's two ways to fix this:
- Do a full update on every change. Slow.
- Detect the number of lines that have been dropped on each change and adjust the result list accordingly. Much better.

Looking at `termout.c`, it looks `term_write` calls `write_char`, which is responsible for appending new lines as necessary. If `write_char` were to return whether the written character resulted in a new line, that would be enough information to hint to `term_schedule_search_partial_update`. Alternatively, if all lines had a unique id, I could drop results from the search buffer until I reach that id. Feedback appreciated on which option sounds best.

**Comment by mintty** [comment]
> * Do a full update on every change. Slow.

You means replace `term_schedule_search_partial_update()` with `term_schedule_search_update()` by the end of term_write? Works fine. I don't see at first glance that it would become too slow but with lots of output maybe.

> If `write_char` were to return whether the written character resulted in a new line, that would be enough information to hint to `term_schedule_search_partial_update`.

Feasible, but the current match positions would also be invalidated if you just modify a line or insert/delete characters in it. It might rather be easier to mark lines as "dirty", to be rematched. On that matter, I'm wondering whether it would have been easier to attach matching positions to the respective lines in the first place, rather than keep them in a global list as seems to be the case. However, that wouldn't fix the problem of changed lines either, so it's probably not useful to change that now.
From what I see, `scrollback_push` cannot help much as it seems to be used for "scrolled out" lines (which are compressed on this occasion, which does not seem too useful these days), so it would split the problem into two cases which are both to be considered (inserting/deleting/modifying visible screen lines will also affect the valid match positions).
Proceed as you feel safe and easy.

**Comment by mintty** [comment]
@kiwiz
I guess my previous argument was not valid as contents is modified within the current screen area only (which is already updated with the _partial_ call) and not in the scrollback buffer, so the trick might actually work. However, I think, I'll simply drop the _partial from the update for the forthcoming release, to have a fix, and leave it up to you whether you'd like an optimisation.

Any ideas about the other issue (where I reused match highlighting for prompt highlighting)?

**Comment by kiwiz** [comment]
@mintty sounds good. I'm on a trip atm, but I can take a look next week.

**Comment by mintty** [comment]
Released 2.7.6.

**Comment by kiwiz** [comment]
@mintty Regarding #569, I believe removing the `win_update();` gives the correct behaviour.

**Comment by kiwiz** [comment]
For this issue (#85) performance for searching seems reasonable! However if someone complains, I'll take a closer look.

**Comment by mintty** [comment]
Great, thanks.
Concerning 569, removing win_update makes even normal scrolling "laggy". Adding an unconditional do_update helps; that's not an option within the previous logic of update handling however, but I'll change it anyway.

**Comment by mintty** [comment]
Released 2.8.4, fixing mouse function in search bar (broken since 2.8.2).
